### ISSUE TITLE
EXISTINGINFRA_CONTROLLER_IMAGE environment variable is not updated

### ISSUE THREAD

**Issue by bboreham** [weaveworks/cluster-api-provider-existinginfra#50]
Evidence:

```
      containers:
      - args:
        - --verbose
        env:
        - name: EXISTINGINFRA_CONTROLLER_IMAGE
          value: docker.io/weaveworks/cluster-api-existinginfra-controller:v0.0.6
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/weaveworks/cluster-api-existinginfra-controller:v0.1.0
```

I suspect the bug is here: https://github.com/weaveworks/cluster-api-provider-existinginfra/blob/e84a7fd4aac08adedd36efff3213bddf252db077/pkg/apis/wksprovider/machine/os/os.go#L578-L583
